spring.application.name=dreamworld-api

# H2 Console — acesse: http://localhost:8080/h2-console
spring.h2.console.enabled=true

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger UI — ordena tags e operações
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method
springdoc.api-docs.path=/api-docs
spring.hateoas.mediatype.hal-forms.enabled=true